version: '3.8'

services:
  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=ecstasify
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ecstasify
    ports:
      - '5432:5432'
    networks:
      - network
    volumes:
      - db:/var/lib/postgresql/data

  mongodb:
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=ecstasify
    ports:
      - '27017:27017'
    networks:
      - network
    volumes:
      - mongodb_data:/data/db

networks:
  network:
    driver: bridge

volumes:
  db:
  mongodb_data:
