name: Server CD

on:
  push:
    branches: [dev]
    paths:
      - 'server/**'
  workflow_dispatch:

jobs:
  upload-artifact:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server

    steps:
      - uses: actions/checkout@v3

      - name: Zip all files for upload between jobs
        run: zip --symlinks -r nest.zip ./*

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: ./server/nest.zip

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: upload-artifact
    environment:
      name: 'server-production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'ecstasify-api'
          slot-name: 'production'
          publish-profile: ${{secrets.ECSTASIFY_API_PUBLISH_PROFILE}}
          package: nest.zip

      - name: Delete zip file
        run: rm nest.zip
