name: Server CI

on:
  push:
    paths:
      - 'server/**'
  pull_request:
    paths:
      - 'server/**'

jobs:
  build-lint-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        run: npm ci

      - name: Format and lint
        run: npm run format-and-lint

      - name: Run tests
        run: npm run test

      - name: Build
        if: github.ref == 'refs/heads/dev'
        run: npm run build

      - name: Zip all files for upload between jobs
        if: github.ref == 'refs/heads/dev'
        run: zip --symlinks -r nest.zip ./*

      - name: Upload artifact for deployment job
        if: github.ref == 'refs/heads/dev'
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: nest.zip

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build-lint-and-test
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    if: github.ref == 'refs/heads/dev'

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'ecstasify-api'
          slot-name: 'production'
          publish-profile: '<publishData><publishProfile profileName="ecstasify-api - Web Deploy" publishMethod="MSDeploy" publishUrl="ecstasify-api.scm.azurewebsites.net:443" msdeploySite="ecstasify-api" userName="$ecstasify-api" userPWD="ikJGB5B51hggoZDfs9wnGlHiBqjNK5L8ysW3x9nWb0ht94vYvBmK0D7mJQL7" destinationAppUrl="https://ecstasify-api.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="http://windows.azure.com" webSystem="WebSites"><databases /></publishProfile><publishProfile profileName="ecstasify-api - FTP" publishMethod="FTP" publishUrl="ftps://waws-prod-bay-175.ftp.azurewebsites.windows.net/site/wwwroot" ftpPassiveMode="True" userName="ecstasify-api\$ecstasify-api" userPWD="ikJGB5B51hggoZDfs9wnGlHiBqjNK5L8ysW3x9nWb0ht94vYvBmK0D7mJQL7" destinationAppUrl="https://ecstasify-api.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="http://windows.azure.com" webSystem="WebSites"><databases /></publishProfile><publishProfile profileName="ecstasify-api - Zip Deploy" publishMethod="ZipDeploy" publishUrl="ecstasify-api.scm.azurewebsites.net:443" userName="$ecstasify-api" userPWD="ikJGB5B51hggoZDfs9wnGlHiBqjNK5L8ysW3x9nWb0ht94vYvBmK0D7mJQL7" destinationAppUrl="https://ecstasify-api.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="http://windows.azure.com" webSystem="WebSites"><databases /></publishProfile></publishData>'
          package: nest.zip

      - name: Delete zip file
        run: rm nest.zip
