name: Server CI

on:
  push:
    paths:
      - 'server/**'
  pull_request:
    paths:
      - 'server/**'

jobs:
  build-lint-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server

    steps:
      - uses: actions/checkout@v3

      - name: Zip all files for upload between jobs
        if: ${{ github.ref == 'refs/heads/chore/#7/setting-up-ci-for-server-deploy' }}
        run: zip --symlinks -r nest.zip ./*

      - name: Upload artifact for deployment job
        if: ${{ github.ref == 'refs/heads/chore/#7/setting-up-ci-for-server-deploy' }}
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: ./server/nest.zip

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build-lint-and-test
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    if: ${{ github.ref == 'refs/heads/chore/#7/setting-up-ci-for-server-deploy' }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'ecstasify-api'
          slot-name: 'production'
          publish-profile: ${{secrets.ECSTASIFY_API_PUBLISH_PROFILE}}
          package: nest.zip

      - name: Delete zip file
        run: rm nest.zip
